name: Reusable CalVer Release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpver

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        run: bumpver update --no-commit

      - name: Extract Version
        id: extract_version
        run: |
          NEW_VERSION=$(grep -m 1 '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Fetch Central cliff.toml
        run: curl -O https://raw.githubusercontent.com/aurumorinc/.github/main/cliff.toml

      - name: Generate Changelog
        run: git-cliff --config cliff.toml --tag ${{ env.NEW_VERSION }} -o CHANGELOG.md

      - name: Commit & Push
        run: |
          git add -u
          git add CHANGELOG.md
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push origin main --tags

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.RELEASE_TOKEN }}